// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6zTwgi31j21OAGe1nsON4nEotZ3WdkY',
    appId: '1:187356985024:web:73cbbc756964dba635df25',
    messagingSenderId: '187356985024',
    projectId: 'budget-buddy-dfe65',
    authDomain: 'budget-buddy-dfe65.firebaseapp.com',
    storageBucket: 'budget-buddy-dfe65.firebasestorage.app',
    measurementId: 'G-QGQ11BXYV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3vlAj54pxfA7qWxR9vlTAvEkvE2sAMNI',
    appId: '1:187356985024:android:66f0add1f60163ab35df25',
    messagingSenderId: '187356985024',
    projectId: 'budget-buddy-dfe65',
    storageBucket: 'budget-buddy-dfe65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF04-VZs01ukIzQlM1XFeTVM7OxspzVDY',
    appId: '1:187356985024:ios:94849156169958d935df25',
    messagingSenderId: '187356985024',
    projectId: 'budget-buddy-dfe65',
    storageBucket: 'budget-buddy-dfe65.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
